### ISSUE TITLE
Bug: a course with no grade data prevents subsequent course data from displaying

### ISSUE THREAD

**Issue by g-luo** [asuc-octo/berkeleytime#420]
This course has no data, yet it shows up in grades

**Comment by THE-COB** [comment]
I don't see this showing up in grades anymore

**Comment by zacharyzollman** [comment]
I am still able to replicate this issue. In addition to COMPSCI C182 lacking grade data, I was unable to add grade data for other classes once I had (tried to) add COMPSCI C182. For example, below is what I saw when I added BIO 1B, then COMPSCI C182, then BIO 1A.

<img width="1108" alt="Screenshot 2023-01-25 at 4 37 22 PM" src="https://user-images.githubusercontent.com/85812228/214727389-e4c87945-28f3-4ffe-ba47-4b5c51ced73a.png">

**Comment by mathhulk** [comment]
Accessing `numerator` of an array which is undefined (no data from backend):
```js
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'numerator')
    at index-65ed57aa.js:523:28665
    at Array.map (<anonymous>)
    at d9 (index-65ed57aa.js:523:28610)
    at index-65ed57aa.js:523:18546
    at E (<anonymous>:1:33304)
    at I (<anonymous>:1:33591)
    at <anonymous>:1:37871
    at Object.d [as dispatch] (index-65ed57aa.js:523:17588)
    at e (<anonymous>:1:38882)
    at index-65ed57aa.js:523:19413```

**Comment by mathhulk** [comment]
The new Berkeleytime rewrite will address this issue.
