### ISSUE TITLE
DATA C100 Spring 2020

### ISSUE THREAD

**Issue by g-luo** [asuc-octo/berkeleytime#423]
From Reddit: 
> hey jw, why isnt data 100's spring 2020 (or offerings of data 100 as compsci c100) not on berkeleytime?

**Comment by zacharyzollman** [comment]
DATA C100 Spring 2020 grade data is currently available. Enrollment data is not available, which suggests that we did not record that data. If we don't have that data, there's not much we can do at this point.

<img width="1170" alt="Screenshot 2023-01-25 at 4 48 16 PM" src="https://user-images.githubusercontent.com/85812228/214729406-ee74900b-496b-4686-9011-641c51c503f2.png">
