### ISSUE TITLE
Visual Bug with Site

### ISSUE THREAD

**Issue by g-luo** [asuc-octo/berkeleytime#464]
e.v.nguyen@berkeley.edu
Go to enrollment section of the website. Search and add CS 170. When it displays after you've added this class, the last word of the class isn't shown because it is cutoff and there is other text overlaid on top of it. For example, instead of displaying "Efficient Algorithms and Intractable Problems" it only displays "Efficient Algorithms and Intractable" with only the top of the word "Problems" showing.
"Chrome
MacOS"

**Comment by THE-COB** [comment]
I could be wrong, but I think with the latest UI change that issue no longer exists. I may not be reproducing it correctly though.

**Comment by zacharyzollman** [comment]
I think this is still an issue, although the amount of text that is cut off is slightly different on my device.
https://berkeleytime.com/enrollment/0-2340-spring-2022-392072
<img width="433" alt="Screen Shot 2022-10-14 at 6 26 59 PM" src="https://user-images.githubusercontent.com/85812228/195962914-f5079b01-0a3c-4c09-a529-8c0968284b0d.png">

**Comment by QxBytes** [comment]
Resolved in #581
