### ISSUE TITLE
Econ 155 Error

### ISSUE THREAD

**Issue by g-luo** [asuc-octo/berkeleytime#469]
Hi, I found a pretty curious bug in berkeleytime. I was on the grades window and I tried to select the class econ 155 in the dropdown menu and suddenly the screen went blank. I tried clearing cookies and disabling ad-blockers and stuff but the problem persisted. I was curious so I checked inspect element. I noticed how whenever a dropdown is selected, it makes a GET request to /API/grades/coures_grades/:number (along with like a thousand requests to google fonts but that's neither here nor there). The request returned 200 and I was even able to make the GET request from my browser and view the JSON response (https://berkeleytime.com/api/grades/course_grades/2046/). On the console, however, there was an uncaught promise from your react-select module (I have attached an image below). I have not been able to figure out why it happens with this course and I haven't run a full test to see if it happens with any others. While I am tempted to full send into this peculiar issue, I really gotta study for 16b so I figured I'd just let you know. If you have any questions for me just shoot me an email.
![image](https://user-images.githubusercontent.com/36020488/118189125-3bb55b80-b3f6-11eb-9030-4c40ba16cf74.png)

Followup:

Ok I know said I was gonna study for 16b but I think I figured out the error. The exception is complaining about a label being undefined or null, and sure enough, if you look at the json for the class, one of the labels is empty! 

[{"instructor": "LOUGH, J", "semester": "spring", "year": "2019", "section_number": "1", "grade_id": 403056}, {"instructor": "EGAN, E", "semester": "fall", "year": "2018", "section_number": "1", "grade_id": 399867}, {"instructor": "LOUGH, J", "semester": "spring", "year": "2018", "section_number": "1", "grade_id": 386534}, {"instructor": "LOUGH, J", "semester": "fall", "year": "2016", "section_number": "1", "grade_id": 357395}, {"instructor": "", "semester": "summer", "year": "2016", "section_number": "1", "grade_id": 416829}, {"instructor": "EGAN, E", "semester": "fall", "year": "2015", "section_number": "1", "grade_id": 363558}, {"instructor": "KLINE, P", "semester": "spring", "year": "2015", "section_number": "1", "grade_id": 373715}, {"instructor": "EGAN, E", "semester": "fall", "year": "2014", "section_number": "1", "grade_id": 348966}, {"instructor": "JANSSON, M", "semester": "summer", "year": "2014", "section_number": "1", "grade_id": 417707}, {"instructor": "EGAN, E", "semester": "fall", "year": "2013", "section_number": "1", "grade_id": 375662}, {"instructor": "ROMER, D", "semester": "summer", "year": "2013", "section_number": "1", "grade_id": 382772}, {"instructor": "EGAN, E", "semester": "fall", "year": "2012", "section_number": "1", "grade_id": 369965}, {"instructor": "KLINE, P", "semester": "spring", "year": "2012", "section_number": "1", "grade_id": 366901}, {"instructor": "KLINE, P", "semester": "spring", "year": "2011", "section_number": "1", "grade_id": 355931}]

**Comment by THE-COB** [comment]
Hi, I'm the person who originally sent bug report in an email. I checked again and it appears the dropdown now just ignores the semester with the blank instructor. I think it makes sense for it to behave like that, should it show a blank instructor instead?

**Comment by g-luo** [comment]
We do indeed have a filter on the backend to omit entries with blank instructors / data. I haven't looked into this bug too much, but if our API returns data for this class then all of this behavior is unwanted and the ideal would be to render the data we have in Grades.

**Comment by THE-COB** [comment]
Would the ideal to be to just show the instructor as blank?

**Comment by THE-COB** [comment]
Oh boy I was wrong I was just able to reproduce the error on the live site

**Comment by THE-COB** [comment]
Ok this just gets better and better: I looked at the big ass csv files under backend/grades/resource/raw for the semester that the data was missing on the json response on the front end and it turns out you guys actually have a professor name for that! So I don't know what is going on anymore.

**Comment by hi-usui** [comment]
@THE-COB Hey, appreciate you sharing your findings. A bit off-topic but how were you able to find this official repo? It doesn't show up in any Google results directly, and we haven't linked to it anywhere on the site. Out of curiosity

**Comment by hi-usui** [comment]
@THE-COB While we can't share our SIS keys because SIS gets pissed like that and they also don't want to give us developer environment keys, since you've started taking a look into it, if you want to try some guess-coding, you can try pushing a branch with your changes and it should automatically deploy on the internet with our private keys

**Comment by g-luo** [comment]
@hi-usui they emailed the octo.berkeleytime account with a detailed bug report and I directed them here

**Comment by THE-COB** [comment]
Oh yeah hi sorry I hope I didn't do anything I wasn't supposed to do. I haven't looked at it since this afternoon but I might start guess coding tomorrow. To be completely honest I was sorta hesitant to clone the repo cause I didn't wanna deal with like however many gigabytes of csv files you got stored. Do you know where I could find the code that handles the GET requests to the API? I'm not super familiar with this code yet.

**Comment by g-luo** [comment]
You're good @THE-COB we still haven't figured out a system for open source development yet -- it's not fully possible for open source folks to test their code since we require API keys (although @hi-usui maybe we can just create dummy backend data for open source dev = no need for sensitive keys). You haven't done anything wrong; in fact we're happy that you're interested in contributing!

Most of our GET requests on the frontend are done in redux (https://github.com/asuc-octo/berkeleytime/tree/master/frontend/src/redux) but it depends on the component and the functionality you're targeting.

**Comment by THE-COB** [comment]
I'm happy to help! I was actually asking about where in the backend the GET requests are handled because I think that's where the issue is. I may have a fundamental misunderstanding about the infrastructure of this site but I think there's something up with how the backend is parsing the csv files and returning the json object because the response has missing profs and the csv files have those profs. Idk if that makes any sense, it's just what it appears like to me.
