### ISSUE TITLE
Clarity Around Grade Distributions

### ISSUE THREAD

**Issue by g-luo** [asuc-octo/berkeleytime#470]
![Screen Shot 2021-05-14 at 7 08 34 PM](https://user-images.githubusercontent.com/36020488/118345201-cde95c80-b4e7-11eb-948b-50f7d4945def.png)

We should more clearly explain how we compute percentiles / factor in PNP.

**Comment by kevinzwang** [comment]
Would we like to calculate percentiles based on both letter and P/NP grades? What would be the benefit for students to do so?

**Comment by g-luo** [comment]
I think students have an overoptimistic view of how many people get As because we include PNP in the percentage.

**Comment by QxBytes** [comment]
Resolved in #579
