### ISSUE TITLE
Scheduler lists 12 am instead of 12 pm

### ISSUE THREAD

**Issue by zacharyzollman** [asuc-octo/berkeleytime#474]
<img width="115" alt="Screen Shot 2021-11-16 at 10 05 29 AM" src="https://user-images.githubusercontent.com/85812228/142040935-cd515e08-d9f3-4d46-95c8-68c30fcce9b7.png">

On the Scheduler tool, I believe the time between 11 am and 1 pm should appear as 12 pm, not 12 am.

**Comment by hi-usui** [comment]
https://github.com/asuc-octo/berkeleytime/pull/475
https://github.com/asuc-octo/berkeleytime/pull/479
