### ISSUE TITLE
unable to build the repo

### ISSUE THREAD

**Issue by zacharyzollman** [asuc-octo/berkeleytime#476]
I couldn't get it to build. I followed both local development guides I found, and couldn't get past the first step on either one.

The `make up` command mentioned in [the wiki](https://github.com/asuc-octo/berkeleytime/wiki/Quick-Setup-Guide) resulted in an error that said the `.env.dev` did not exist. The `make init` command mentioned in [the setup md](https://github.com/asuc-octo/berkeleytime/blob/master/setup.md) does not seem to work either, it looks like the make file doesn't have an init method. Are other people able to perform this procedure?

**Comment by g-luo** [comment]
Hi @zacharyzollman, this error is likely because you don't have the secret keys that is necessary to access our databases / backend infrastructure. 

@hi-usui is there static data external contributors can use, or is it possible to share keys privately?

**Comment by hi-usui** [comment]
@zacharyzollman

@g-luo is correct. I spent 6 months in the Fall going back and forth with SIS (https://api-central.berkeley.edu/apis) trying to get an extra set of development keys that the wider community can use. They absolutely will not consider for us rate-limited keys or a dev environment for the public.

Here's what we can do: We can start planning for a full replication of the development db to a public one every night. However the full Postgres db is unwieldly in its current state. I'll update this once we can improve the db and make it publicly available

**Comment by hi-usui** [comment]
working on making it so the full SIS API's data set is available, pre-processed, so we can avoid pissing off SIS without exposing their API to outside requests

**Comment by hi-usui** [comment]
@zacharyzollman We have progress on making the new backend/our entire data set accessible for open-source without needing SIS API keys. The new backend isn't ready for prod, but I'd appreciate it greatly if you could try running it. We have basic SIS Class/CalAnswers Grade queries prepared in Postman ([postman.json](https://github.com/asuc-octo/berkeleytime/blob/d718ab01032b6aa3703485a87a22561e527a01ce/backend/postman.json)). If you're still interested, we can share the mirror to our database on Discord, and maybe collaborate, even.

Inside [backend-node](https://github.com/asuc-octo/berkeleytime/tree/43972ddbc3e158528db81d74f2e8831fe16b72e4/backend): `npm install`, `npm run dev`. Needs Node >= v16.14, MongoDB ≈4.4+, Redis).

**Comment by zacharyzollman** [comment]
@hi-usui awesome! I would be happy to try it out but it might be a little while because I have a lot going on at the moment. If anything comes up, is this the best place to ask questions?

**Comment by hi-usui** [comment]
Sounds good, take it at your leisure. Unless we start seeing overconsumption/malicious traffic due to bad actors/GitHub scrapers, the mirror to the non-production database is mirrored nightly and can be downloaded [here](https://storage.googleapis.com/berkeleytime/public/mdb.tar)
