### ISSUE TITLE
Scheduler Onboarding

### ISSUE THREAD

**Issue by christinas24** [asuc-octo/berkeleytime#491]
**Select Classes page**
- [ ] option to add all saved classes
- maybe streamline UI more

**Time Preferences page**
- [ ] disallow end time before start time
- [ ] allow removing created time block
- [ ] clear selection values after adding new block
 
**overall**
- [ ] connect onboarding to main scheduler view
- [ ] add back button
- [ ] add exit button?

**Comment by mathhulk** [comment]
The new Berkeleytime rewrite will address this issue.
