### ISSUE TITLE
Implement email notifications or remove them from Settings

### ISSUE THREAD

**Issue by Gabe-Mitnick** [asuc-octo/berkeleytime#508]
# Problem
In the [Profile page](https://berkeleytime.com/profile) (which seems more like Account Settings) there's a Notifications section to enable email notifications, but Christina says the email notifications don't actually exist. Users are misled.

# Solution
Check if email notifications are implemented on backend. If the backend is already all set up, integrate the settings on the frontend with the backend, so that the email notifications actually work. If the backend isn't ready, decide if we really want to have email notifications on the roadmap. If we do, comment out the "Notifications" section for now, but create an Issue to bring back the section in the future when we're ready. If we don't, delete the "Notifications" section and all associated code (to leave the codebase cleaner than we found it 😌).

# Acceptance criteria
Notifications settings are visible <=> Notifications actually work

**Comment by mathhulk** [comment]
We removed email notifications.
