### ISSUE TITLE
Scheduler [Feature Request] - Exam Schedule

### ISSUE THREAD

**Issue by danieljbk** [asuc-octo/berkeleytime#545]
Do you have any plans on having the exam schedule, well, anywhere? Could show exam conflicts, or simply be exported with the rest of the calendar.

**Comment by mathhulk** [comment]
Not sure about the availability of exam data, but we could use tabs and allow users to switch between class and exam views. I had quickly sketched up a more user-friendly design for the scheduler which I was hoping we could focus on more this semester and I've attached it below.

![Frame 1](https://user-images.githubusercontent.com/19879953/213293922-0acb8fb2-66c5-4d47-96b8-a3fb3f62983c.png)

**Comment by mathhulk** [comment]
The new Berkeleytime rewrite will address this issue.
