### ISSUE TITLE
Weird Search Ranking

### ISSUE THREAD

**Issue by akmazian** [asuc-octo/berkeleytime#569]
For some reason, when I tried searching for Chem 3b:
- if I typed *chem 3*
  - **CHEM 3B** appears first, then **CHEM 3A**
- if I typed *chem 3b*
  - **CHEM 3BL** appears first, then **CHEM 120B**, **CHEM 253B**, **CHEM 263B**, and then **CHEM 3B**

It doesn't really produce anything wrong, it's just the ranking is a bit confusing and sometimes require users to spend extra time to find their class when they are trying to be specific with their search string.

**Comment by Jdyn** [comment]
Hello my friend, I am going to work on this because you raise really good points.

You can check the progress [here](https://search.berkeleytime.com/).

**Comment by akmazian** [comment]
:)

**Comment by zacharyzollman** [comment]
We did work on this a bit last semester; see #515 and the [improve-search-2](https://github.com/asuc-octo/berkeleytime/tree/improve-search-2) branch.

**Comment by Jdyn** [comment]
Yes I did see that and Ihave taken some inspiration from it. My version also currently spans into the enrollment and grades class drop downs such that you can type things like "cs" and "16b" and get the expected results as well.
