### ISSUE TITLE
Broken Link @ Profile > Support > Report a bug

### ISSUE THREAD

**Issue by akmazian** [asuc-octo/berkeleytime#570]
*sorry about all the posts*

The link on `Profile` > `Support` > `Report a bug` (i.e. `'/bugs'`) seems to be broken

**Comment by zacharyzollman** [comment]
Hi! No worries, thanks for the input! I believe we are planning to remove parts of the `Profile` tab, including the link to the old bug report form. I think @QxBytes is planning to do this?

**Comment by mathhulk** [comment]
We removed the ability to report a bug from the Support page.
