### ISSUE TITLE
Scheduler: Uppercase search yields no results

### ISSUE THREAD

**Issue by cwangsanata** [asuc-octo/berkeleytime#585]
### Issue:
Searching for classes in the scheduler using uppercase characters yields no results. Mixing cases also yields no results.

### Searching for 'data':
![lower](https://github.com/asuc-octo/berkeleytime/assets/75346952/0053d049-9916-4664-873c-549038d2661d)

### Searching for 'DATA':
![upper](https://github.com/asuc-octo/berkeleytime/assets/75346952/570773bb-48e2-4233-a5e8-6ea414988dcd)

**Comment by mathhulk** [comment]
Thanks for letting us know! We'll be looking into this!

**Comment by Jdyn** [comment]
This is inadvertently already fixed in #575 but it's not merged into production yet.

**Comment by cwangsanata** [comment]
Feature working; Uppercase search yields equivalent results.

![image](https://github.com/asuc-octo/berkeleytime/assets/75346952/24a78779-599e-4a5d-b65e-617fc04e36ed)

![image](https://github.com/asuc-octo/berkeleytime/assets/75346952/b6dbb67d-8c45-4b52-bd75-07f19ca59b20)
