### ISSUE TITLE
Error while exporting to calendar

### ISSUE THREAD

**Issue by sondresorbye** [asuc-octo/berkeleytime#587]
I am getting this error when trying to export to my calendar:

index-079878da.js:37 Uncaught RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at n (SchedulerCalendar-53d23c9d.js:1:38863)
    at SchedulerCalendar-53d23c9d.js:9:36
    at Array.map (<anonymous>)
    at Wo (SchedulerCalendar-53d23c9d.js:1:39078)
    at x (Callout-ae4d6a55.js:1:24691)
    at Object.cA (index-079878da.js:37:9855)
    at dA (index-079878da.js:37:10009)
    at pA (index-079878da.js:37:10066)
    at ig (index-079878da.js:37:31466)

**Comment by Jdyn** [comment]
Hey @sondresorbye before I look into it, would it be possible if you could provide the selected classes that were in the schedule at the time of the error?

**Comment by sondresorbye** [comment]
Thanks for looking at this. Here is the calendar: https://berkeleytime.com/schedule/432e28b9-b34d-44e3-bf39-fc236ee7338e

**Comment by cwangsanata** [comment]
Seconding the error; a similar console error occurs when having a class on a weekend. Removing the ASAMST class (which occurs on a Sunday to represent an online class) resolves this issue and I can generate the Calendar file. 

Here is my calendar: https://berkeleytime.com/scheduler/6065cb63-01e9-4c85-8c9f-86299d38bb23

**Comment by Jdyn** [comment]
@sondresorbye @cwangsanata Hey thank you for all the information. If you have time, try exporting you calendars here with a potential fix: https://export-schedule-date-bug.berkeleytime.com

**Comment by sondresorbye** [comment]
I cannot login. The export-schedule-date-bug subdomain is probably not whitelisted for Google auth. Here is the error:
`Error 400: redirect_uri_mismatch`

**Comment by Jdyn** [comment]
Yeah sorry that is a side effect of this testing environment. You may recreate the schedule and attempt to export without logging in if you have time.

**Comment by cwangsanata** [comment]
Adding the problematic class (ASAMST 20AC)  to the calendar and exporting the calendar appears to work on my end.
