### ISSUE TITLE
Element overflow post 8PM class

### ISSUE THREAD

**Issue by cwangsanata** [asuc-octo/berkeleytime#591]
Inserting a class that goes past 7PM causes some overlap with the footer of the site.

![image](https://github.com/asuc-octo/berkeleytime/assets/75346952/eeaf9048-7f69-4d4a-83f7-dda65ddef018)

**Comment by mathhulk** [comment]
Thanks for letting us know!

**Comment by mathhulk** [comment]
The new Berkeleytime rewrite will address this issue.
