### ISSUE TITLE
Catalog course tabs and section links

### ISSUE THREAD

**Issue by mathhulk** [asuc-octo/berkeleytime#603]
@HenricZh started #572 to add tabs to the catalog for displaying grade and enrollment information for the selected course. @Jdyn refactored the catalog before the tabs were merged and now the additions are outdated. The tabs need to either be refactored themselves or rewritten, but the majority of the logic works.

[Figma](https://www.figma.com/file/qvhrQhhU6URKaphzXqNuqd/Catalog-Tabs?node-id=101%3A3&t=mputFx5oa4liOFCQ-0)
[Original bug bash reference](https://www.notion.so/berkeleytimeteam/a90a7246e6d04b7cb6d76b535d60202b?v=13a953f48227432eb6f9556708751ec4&pvs=4)

- [ ]  Catalog tabs
  - [ ] Use the design from Figma (proposed by the design team)
  - [ ] Address all critical bugs and research from the bug bash
- [ ]  Link to the official course catalog for sections
  - [ ]  Include a link icon to differentiate the link from other text

**Comment by Jdyn** [comment]
Will see through on this. Let's get #592 in before I begin.

**Comment by mathhulk** [comment]
The new Berkeleytime rewrite will address this issue.
