### ISSUE TITLE
Bug: Logging out does not register until a full page refresh

### ISSUE THREAD

**Issue by Jdyn** [asuc-octo/berkeleytime#609]
Apollo client caches the user object upon successful authentication. Once the user clicks log out, the apollo cache does not seem to clear the user data from the cache so the application still believes the user is logged in.

There is currently a mechanism that is supposed to clear the cache which I assume worked before. Currently the mechanism doesn't work so something must have changed in the configuration.

**Comment by mathhulk** [comment]
The new Berkeleytime rewrite will address this issue.
