### ISSUE TITLE
GraphQL Onboarding: Chat app

### ISSUE THREAD

**Issue by maxmwang** [asuc-octo/berkeleytime#615]
Create a new complete module following our file structure. This module creates a chat app with 1 query and 1 mutation:

- query: find all messages, optionally filtering by user
- mutation: send a message containing user and message body. store this data in Mongo with a timestamp. 

Make sure to follow the file structure for our current modules! ie.:
- typedefs
- controller
- resolver
- formatter

Do this in a branch off of the `gql` branch, and submit a PR once you are done, tagging this issue and adding @maxmwang and @kevinzwang as reviewers

**Comment by Jdyn** [comment]
This seems to be done. Feel free to reopen.
