### ISSUE TITLE
Fix scheduler module

### ISSUE THREAD

**Issue by Chengming-Li** [asuc-octo/berkeleytime#642]
Rewrite mongo schema, graphql typedef, and maybe the queries and mutations
Each course should have one primary section id, and multiple secondary section ids
Each schedule will have multiple classes
Rewrite the schema to show the relationship between the course id, the primary section id, and the secondary section ids

**Comment by maxmwang** [comment]
Current backend's "typedef" equivalent: [here](https://github.com/asuc-octo/berkeleytime/blob/master/backend/scheduler/schema.py)


Models: [here](https://github.com/asuc-octo/berkeleytime/blob/master/backend/scheduler/models.py)

**Comment by maxmwang** [comment]
Overview:

Current model is defined incorrectly. Refer to prouction backend for a correct implementation. Basic outline: relationship between `class_id`, `primary_section_id`, and `secondary_section_id` is not defined. 

Changes will propogate through module.
