### ISSUE TITLE
schedule disappeared

### ISSUE THREAD

**Issue by Mehvix** [asuc-octo/berkeleytime#717]
My fall 2024 schedule doesn't show up on my dashboard and I'm fairly certain I didn't delete it. The rest of my schedules from prior semesters are still present. I found the [schedule link](https://berkeleytime.com/scheduler/2984ae80-e338-43cd-8700-d261229f5642) in my history, but going to the page returns "Invalid Schedule ID".

**Comment by mathhulk** [comment]
Hey @Mehvix! Unfortunately, we ran into some issues recently which might have caused data from the past 2 months to be lost. We are working to try and get this data back, but we apologize for the inconvenience in the meantime! Please reach out to us on [Discord](https://discord.gg/uP2bTPh99U) for more information.
